### ISSUE TITLE
Sugestão: Redundância de "Pront Tech"s

### ISSUE THREAD

**Issue by alex-custodio** [ceduardoferreira/ladingpage-pronttech#2]
### Existem dois blocos mostrando basicamente o mesmo conteúdo:
O "Pront Tech" a esquerda poderia ser substituído por algum texto de título ou outra ideia
<br>
![Sem título](https://user-images.githubusercontent.com/89322317/181751314-3654c0ae-b622-488e-95ec-fa624a39546d.png)

**Comment by ceduardoferreira** [comment]
Completa. Commit "removendo redudâncias"
