### ISSUE TITLE
Alterações simples

### ISSUE THREAD

**Issue by ceduardoferreira** [ceduardoferreira/ladingpage-pronttech#3]
1. Alterar o nome "Pront Tech", no conteúdo principal para "PRONT TECH".
2. Dimunuir o espaço entre os itens do centro.
3. Colocar link do instagram no botão.

**Comment by alex-custodio** [comment]
essas são as alterações que vc já fez ou vai fazer?

**Comment by ceduardoferreira** [comment]
Já fiz
